[package]
name = "serde-big-array"
version = "0.1.5"
authors = ["est31 <MTest31@outlook.com>", "David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Big array helper for serde."
documentation = "https://docs.rs/serde-big-array"
repository = "https://github.com/est31/serde-big-array"
readme = "README.md"
exclude = ["/sgx/*"]

[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }

[dev-dependencies]
serde_json = "1.0"

[features]
const-generics = []
